name: Unit Tests
on: push 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          testMode: all  # Runs both Edit Mode & Play Mode tests
          artifactsPath: artifacts/  # Stores test results in this folder

      - name: Save Test Results  # Uploads the test results as an artifact
        if: always()  # Runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: Unit-Test-Results
          path: artifacts/
      - name: Show Test Results in Logs
        if: always()
        run: cat artifacts/test-results.xml || true
