name: Unity CI

on: [push, pull_request] # Runs on every push or pull request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Library folder (to speed up builds)
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ runner.os }}-${{ github.sha }}
        restore-keys: Library-${{ runner.os }}-

    - name: Setup Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 2022.3.8f1  # Change this to match your Unity version
        license: Personal  # This skips license activation

    - name: Build project
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: StandaloneWindows64
        unityVersion: 2022.3.8f1 # Make sure this matches your Unity version
